delimiter $$

CREATE TABLE `fy_dictionary_room` (
  `room_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '房屋ID',
  `house_id` int(10) unsigned NOT NULL COMMENT '楼盘id',
  `seat_id` int(10) unsigned NOT NULL COMMENT '栋座id',
  `unit_id` int(10) unsigned NOT NULL COMMENT '单元ID',
  `room_name` varchar(10) NOT NULL DEFAULT '' COMMENT '房屋户号',
  `room_alias` varchar(20) NOT NULL DEFAULT '' COMMENT '房屋别名 楼层号加房屋户号',
  `room_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '状态 0新建 1有效',
  `room_using` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否启用 1启用0不启用',
  `room_floor_number` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '楼层（在第几楼）',
  `room_use_area` varchar(20) NOT NULL DEFAULT '' COMMENT '套内面积',
  `room_build_area` varchar(20) NOT NULL DEFAULT '' COMMENT '产权面积',
  `room_with_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '朝向ID 1:东2南3西4北',
  `room_type_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '户型ID',
  `room_address` varchar(200) NOT NULL COMMENT '房屋地址',
  `room_basic_decoration` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '装修类型1:精装2:简装3:毛坯4:清水:5:豪装6:统装',
  `room_basic_elevator` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否有电梯 1有0无',
  `room_basic_property` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否有产权 1有0无',
  `room_basic_consign_time` date NOT NULL DEFAULT '0000-00-00' COMMENT '交房日期',
  `room_basic_affiliate_area` varchar(20) NOT NULL DEFAULT '' COMMENT '附属面积',
  `room_basic_affiliate_facility` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '附属设施 1:花园2:露台3:地下室4:阁楼',
  `room_basic_purpose` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '房屋用途 1:住宅-公寓2:住宅-普通住宅3:住宅-别墅4:非住宅-商铺5:非住宅-公建6:非住宅-写字间7:非住宅-车库8:工用-仓库9:工用-厂房',
  `room_basic_actuality` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '房屋现状 1:自住2:闲置3:出售4:出租',
  `room_owner_name` varchar(20) NOT NULL DEFAULT '' COMMENT '产权人姓名',
  `room_owner_country` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '国籍',
  `room_basic_number_level` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '号码等级1:A,2:B,3:C',
  `room_owner_sale_reason` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '售房原因=>1:换房2:儿女上学 ,3:儿女结婚,4: 外迁,5:兑现',
  `room_owner_sex` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '性别 1男0女',
  `room_owner_email` varchar(30) NOT NULL DEFAULT '' COMMENT 'email',
  `room_owner_marital` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '婚姻状况 1:已婚0:未婚  已婚  未婚   离异   丧偶  其他',
  `room_owner_address` varchar(200) NOT NULL DEFAULT '' COMMENT '住址',
  `room_owner_contact` varchar(200) NOT NULL DEFAULT '' COMMENT '产权人联系方式',
  `room_owner_papers_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '证件类型 1:身份证2:驾驶证',
  `room_owner_papers_number` varchar(30) NOT NULL DEFAULT '' COMMENT '证件号码',
  `room_owner_common` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否共有 1共有0不共有',
  `room_owner_coowner` varchar(20) NOT NULL DEFAULT '' COMMENT '共有人姓名',
  `room_owner_agent` varchar(20) NOT NULL DEFAULT '' COMMENT '代理人姓名',
  `room_owner_agent_contact` varchar(200) NOT NULL DEFAULT '' COMMENT '代理人联系方式',
  `room_last_follow_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后一次精耕时间',
  `room_follow_by` int(10) unsigned NOT NULL DEFAULT '0',
  `room_last_modify_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后一次修改时间',
  `room_last_using_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后一次启用时间',
  `room_last_close_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后一次关闭时间',
  `room_create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '添加时间',
  `room_create_by` int(10) unsigned NOT NULL COMMENT '添加人id',
  `room_modify_by` int(10) unsigned NOT NULL COMMENT '修改人id',
  `room_duty_company_id` int(10) unsigned NOT NULL COMMENT '责任部门的公司id（冗余）',
  `room_duty_office` int(10) unsigned NOT NULL COMMENT '责任部门id',
  `room_duty_officer` int(10) unsigned NOT NULL COMMENT '责任人id',
  `room_duty_a` varchar(255) NOT NULL DEFAULT '' COMMENT 'A级共享部门',
  `room_duty_b` varchar(255) NOT NULL DEFAULT '' COMMENT 'B级共享部门',
  `room_duty_c` varchar(255) NOT NULL DEFAULT '' COMMENT 'C级共享部门',
  `housing_level` int(10) unsigned NOT NULL COMMENT '房源等级(冗余)',
  `housing_sale_status` int(10) unsigned NOT NULL COMMENT '房源租售情况(冗余)',
  `room_quality` tinyint(1) unsigned NOT NULL COMMENT '产权性质 1:商品房2:房改房3：拆迁安置房4:安居房5:公房6:经济适用房7:私房',
  `room_audit_status` smallint(1) unsigned NOT NULL DEFAULT '0' COMMENT '审核状态',
  `room_audit_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '审核时间',
  `room_audit_remark` varchar(500) NOT NULL DEFAULT '' COMMENT '审核备注',
  `work_type` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '工作类型',
  `room_if_delete` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '删除状态 0未 1已删除',
  PRIMARY KEY (`room_id`),
  KEY `house_id` (`house_id`)
) ENGINE=InnoDB AUTO_INCREMENT=439 DEFAULT CHARSET=utf8 COMMENT='楼盘字典房屋表'$$

